In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,0],[3,4,5],[4,3,7]])

In [4]:
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[1 2 0]
 [3 4 5]
 [4 3 7]]


In [5]:
print(a.shape)

(3, 3)


In [6]:
b = np.ones((5,3))
print(b)
print(type(b))
print(b.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
(5, 3)


In [21]:
c = np.full((3,2),3, dtype = np.float64)
print(c)
print(c.shape)
print(c.dtype)

[[3. 3.]
 [3. 3.]
 [3. 3.]]
(3, 2)
float64


In [12]:
d = np.eye(4)
print(d)
print(d[  : , 2  ])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0. 0. 1. 0.]


### RandomMatrix

In [19]:
randomMatrix = np.random.random((3,4))
print(randomMatrix)
print(randomMatrix[ 0 , 0 ])

[[0.55717865 0.71143351 0.82453444 0.84735189]
 [0.12196074 0.01390223 0.98388384 0.6360893 ]
 [0.28626281 0.65002126 0.99480855 0.40164341]]
0.5571786454888196


In [22]:
x = np.array([[1,2],[4,7]])
y = np.array([[4,8],[5,1]])

z = x + y
print(z)
print()
print(np.add(x,y))

[[ 5 10]
 [ 9  8]]

[[ 5 10]
 [ 9  8]]


In [25]:
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [4 7]]
[[4 8]
 [5 1]]
[[14 10]
 [51 39]]
[[14 10]
 [51 39]]


In [28]:
i = np.array([1,2,3,4])
j = np.array([1,2,3,4])

print(i.dot(j))
print(np.dot(i,j))

30
30


In [29]:
print(sum(x))

[5 9]


In [30]:
print(np.sum(x))

14


In [31]:
print(a)

[[1 2 0]
 [3 4 5]
 [4 3 7]]


In [32]:
print(i)

[1 2 3 4]


In [33]:
print(j)

[1 2 3 4]


In [34]:
j = j*2
j= j**2

In [35]:
print(j
     )

[ 4 16 36 64]


In [38]:
print(np.stack((i,j), axis = 1))

[[ 1  4]
 [ 2 16]
 [ 3 36]
 [ 4 64]]


## Statistical Functions

In [4]:
a = np.array([1,2,4,6,7,9])

pri

[0 1 3 5 6 8]


In [5]:
a = np.array([[1,2],[4,6]])
b = np.array([[7,2],[3,5]])

print(a.T)

[[1 4]
 [2 6]]
